
"""money convertor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1imuJO42XaZQ6G0iRoJv79HznC2PoGHyD
"""
EXCHANGE_RATE = 89.62  

def usd_to_inr(amount_usd, rate):
    """Converts a US Dollar amount to Indian Rupees using a specified rate."""
    amount_inr = amount_usd * rate
    return amount_inr

def inr_to_usd(amount_inr, rate):
    """Converts an Indian Rupee amount to US Dollars using a specified rate."""
    amount_usd = amount_inr / rate
    return amount_usd

def get_valid_amount():
    """Gets and validates a positive numerical input from the user."""
    while True:
        try:

            amount = float(input("   Enter the amount you want to convert: "))
            if amount >= 0:
                return amount
            else:
                print(" Please enter a non-negative amount.")
        except ValueError:
            print(" Invalid input. Please enter a valid number.")

def get_valid_rate(default_rate):
    """Gets and validates a positive numerical input for the exchange rate."""
    while True:
        try:
            rate_input = input(f"   Enter the new exchange rate (1 USD = ? INR) or press Enter to keep default ({default_rate:.2f}): ")

            if not rate_input:

                return default_rate

            rate = float(rate_input)

            if rate > 0:
                return rate
            else:
                print("    The exchange rate must be a positive number.")
        except ValueError:
            print("    Invalid input. Please enter a valid number for the rate.")

def currency_converter_tool():
    """The main function to run the currency converter application."""
    global EXCHANGE_RATE

    print("\n--- Simple USD/INR Converter ---")
    print("--- Setup Exchange Rate ---")

    new_rate = get_valid_rate(EXCHANGE_RATE)
    EXCHANGE_RATE = new_rate
    print(f"\n Conversion rate set: 1 USD = {EXCHANGE_RATE:,.2f} INR")

    while True:
        print("\n--- Current Rate: 1 USD = **{EXCHANGE_RATE:.2f}** INR ---")
        print("What conversion do you need?")
        print("1. USD to INR (Dollar to Rupee)")
        print("2. INR to USD (Rupee to Dollar)")
        print("3. **Set New Exchange Rate**")
        print("4. Exit")

        choice = input("Enter your choice (1, 2, 3, or 4): ")

        if choice == '1':
            amount = get_valid_amount()
            result = usd_to_inr(amount, EXCHANGE_RATE)
            print(f"{amount:,.2f} USD is equal to {result:,.2f} INR.")

        elif choice == '2':
            amount = get_valid_amount()
            result = inr_to_usd(amount, EXCHANGE_RATE)
            print(f" {amount:,.2f} INR is equal to {result:,.2f} USD.")

        elif choice == '3':
            print("\n---Setting a New Rate ---")
            new_rate = get_valid_rate(EXCHANGE_RATE)
            EXCHANGE_RATE = new_rate
            print(f"\nConversion rate updated: 1 USD = {EXCHANGE_RATE:,.2f} INR")

        elif choice == '4':
            print("\nThank you for using the converter!")
            break

        else:
            print(" Invalid choice. Please enter 1, 2, 3, or 4.")


if __name__ == "__main__":
    currency_converter_tool()